<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    
    
    
    
    <!-- EXE Metadata (Name, Icon, Version, Company) -->
    <AssemblyName>Content-Aware Face Distortion</AssemblyName>
    <ApplicationIcon>nice.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Authors>Aditya Mohanta</Authors>
    <Product>Content-Aware Face Distortion</Product>
    <Description>SEAM CARVING focusing on face area.</Description>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260602" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260602" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ffmpeg\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="nice.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
